# Generated by Django 5.0.7 on 2024-11-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Usuarios",
        ),
    ]
