# Generated by Django 5.0.7 on 2024-10-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telefono_codeudor",
            old_name="cliente",
            new_name="codeudor",
        ),
        migrations.AddField(
            model_name="campañas",
            name="fecha_actualizacion",
            field=models.DateField(default="2024-03-12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuarios",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-05-12 12:00:00Z"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="telefono_cliente",
            name="indicativo",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="telefono_cliente",
            name="tipo",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="telefono_cliente",
            name="tipo_celular",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
