# Generated by Django 5.0.7 on 2024-11-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligaciones',
            name='codigo_obligacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='plan_pago_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obligaciones',
            name='codigo',
            field=models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
