# Generated by Django 5.0.7 on 2024-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tipo_gestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name="chat",
            old_name="usuario",
            new_name="CustomUser",
        ),
        migrations.DeleteModel(
            name="Usuarios",
        ),
    ]
