# Generated by Django 5.0.7 on 2024-10-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="acuerdo_pago",
            name="descripcion",
            field=models.CharField(default="sin descripcion", max_length=60),
        ),
    ]
