# Generated by Django 5.0.7 on 2024-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campañasusuarios",
            name="fecha_asignacion",
            field=models.DateField(auto_now_add=True),
        ),
    ]
