# Generated by Django 5.0.7 on 2024-11-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="estado",
            field=models.BooleanField(default=True),
        ),
    ]
