# Generated by Django 5.0.7 on 2024-12-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultadosgestion",
            name="codigo",
            field=models.CharField(default=123, max_length=8),
            preserve_default=False,
        ),
    ]
