# Generated by Django 5.0.7 on 2025-01-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0002_codigosestado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obligaciones",
            name="codigo_obligacion",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
