# Generated by Django 5.0.7 on 2024-10-31 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0002_acuerdo_pago_descripcion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagos",
            name="cliente",
        ),
    ]
