# Generated by Django 5.0.7 on 2024-11-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0002_obligaciones_codigo_obligacion_pagos_plan_pago_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acuerdo_pago',
            name='cumplimiento',
        ),
        migrations.AddField(
            model_name='acuerdo_pago',
            name='estado',
            field=models.CharField(default='Faltan Dias'),
        ),
    ]
