# Generated by Django 5.0.7 on 2024-10-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0002_alter_campañasusuarios_fecha_asignacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="campañas",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="campañas",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-05-14 16:45:00Z"
            ),
            preserve_default=False,
        ),
    ]
