# Generated by Django 5.0.7 on 2024-11-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0002_customuser_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="estado",
            field=models.BooleanField(default=False),
        ),
    ]
