# Generated by Django 5.0.7 on 2024-12-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0002_passwordchangerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordchangerequest",
            name="changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordchangerequest",
            name="is_changed",
            field=models.BooleanField(default=False),
        ),
    ]
