# Generated by Django 5.0.7 on 2024-11-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0002_tipo_gestion_rename_usuario_chat_customuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestiones",
            name="tipo_gestion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm_api.tipo_gestion",
            ),
            preserve_default=False,
        ),
    ]
