# Generated by Django 5.0.7 on 2024-12-10 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0002_rename_fecha_facturazion_obligaion_obligaciones_fecha_facturacion_obligacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='califiacion_cliente',
            new_name='calificacion_cliente',
        ),
        migrations.RenameField(
            model_name='obligaciones',
            old_name='estado_operaional',
            new_name='estado_operacional',
        ),
        migrations.RenameField(
            model_name='obligaciones',
            old_name='sado_total',
            new_name='saldo_total',
        ),
        migrations.RenameField(
            model_name='obligaciones',
            old_name='valor_gasto_cobranza',
            new_name='valor_gastos_cobranza',
        ),
        migrations.RemoveField(
            model_name='codeudores',
            name='obligacion',
        ),
        migrations.AddField(
            model_name='obligaciones',
            name='codeudor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligaciones', to='crm_api.codeudores'),
        ),
    ]
