# Generated by Django 5.0.7 on 2024-12-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0003_alter_resultadosgestion_descripcion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultadosgestion",
            name="descripcion",
        ),
    ]
