# Generated by Django 5.0.7 on 2025-01-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0003_alter_obligaciones_codigo_obligacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obligaciones",
            name="porc_gastos_cobranza",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="obligaciones",
            name="puntaje_comportamiento",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="obligaciones",
            name="puntaje_credito",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="obligaciones",
            name="tasa_interes",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
