# Generated by Django 5.0.7 on 2024-12-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0003_rename_califiacion_cliente_clientes_calificacion_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obligaciones',
            old_name='feha_castigo',
            new_name='fecha_castigo',
        ),
        migrations.RenameField(
            model_name='obligaciones',
            old_name='feha_corte_obligacion',
            new_name='fecha_corte_obligacion',
        ),
    ]
