# Generated by Django 5.0.7 on 2024-11-14 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0003_remove_acuerdo_pago_cumplimiento_acuerdo_pago_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultadosgestion",
            name="campaña",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm_api.campañas",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="acuerdo_pago",
            name="estado",
            field=models.CharField(default="Vigente"),
        ),
        migrations.AlterField(
            model_name="acuerdo_pago",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="gestiones",
            name="comentarios",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="gestiones",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="obligaciones",
            name="valor_capital",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
