# Generated by Django 5.0.7 on 2024-11-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0003_alter_customuser_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campañas",
            name="fecha_actualizacion",
            field=models.DateField(auto_now_add=True),
        ),
    ]
