# Generated by Django 5.0.7 on 2024-12-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0002_alter_gestiones_fecha"),
        ("crm_api", "0004_passwordchangerequest_is_rejected"),
    ]

    operations = []
