# Generated by Django 5.0.7 on 2024-12-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0004_rename_feha_castigo_obligaciones_fecha_castigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefono_referencia',
            old_name='referecia',
            new_name='referencia',
        ),
    ]
