# Generated by Django 5.0.7 on 2024-11-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "crm_api",
            "0004_resultadosgestion_campaña_alter_acuerdo_pago_estado_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="campañas",
            name="img",
            field=models.URLField(blank=True, null=True),
        ),
    ]
