# Generated by Django 5.0.7 on 2025-01-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0004_alter_obligaciones_porc_gastos_cobranza_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acuerdo_pago",
            name="codigo_resultado_gestion",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="acuerdo_pago",
            name="fecha_gestion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acuerdo_pago",
            name="resultado_gestion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="acuerdo_pago",
            name="estado",
            field=models.CharField(default="Vigente", max_length=20),
        ),
    ]
