# Generated by Django 5.0.7 on 2024-12-20 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0005_alter_obligaciones_codigo_obligacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestiones',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
