# Generated by Django 5.0.7 on 2024-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0005_campañas_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campañas",
            name="img",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
