# Generated by Django 5.0.7 on 2024-12-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0005_merge_20241205_0739"),
        ("crm_api", "0005_merge_20241205_0741"),
    ]

    operations = []
