# Generated by Django 5.0.7 on 2025-01-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0005_acuerdo_pago_codigo_resultado_gestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acuerdo_pago",
            name="codigo_asesor",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="acuerdo_pago",
            name="descripcion",
            field=models.CharField(default="sin descripcion", max_length=255),
        ),
    ]
