# Generated by Django 5.0.7 on 2024-12-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0005_rename_referecia_telefono_referencia_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligaciones',
            name='codigo_obligacion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
