# Generated by Django 5.0.7 on 2024-12-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0006_alter_obligaciones_codigo_obligacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligaciones',
            name='intereses_corriente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='obligaciones',
            name='saldo_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='obligaciones',
            name='saldo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='obligaciones',
            name='valor_cuota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='obligaciones',
            name='valor_iva_gastos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='obligaciones',
            name='valor_obligacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='obligaciones',
            name='valor_ultimo_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='obligaciones',
            name='valor_vencido',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
