# Generated by Django 5.0.7 on 2024-11-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0006_alter_campañas_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campañas",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
