# Generated by Django 5.0.7 on 2025-01-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0009_alter_acuerdo_pago_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivoProcesado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=32, unique=True)),
                ("fecha_procesado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
