# Generated by Django 5.0.7 on 2025-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_api", "0010_archivoprocesado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acuerdo_pago",
            name="codigo_asesor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
